name: testconf_generator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain
    - langchain-huggingface
    - langgraph
    - transformers
    - accelerate
    - torch
    - pyyaml
    - pydantic
    - huggingface_hub
    - accelerate
